### ISSUE TITLE
Exercice pour Kheira

### ISSUE THREAD

**Issue by AlixSil** [ipop-up/doridot-sncell#3]
## Aim
Getting you comfortable with GIT

## Steps

- [x] Download this repository using command line
- [x] Create a branch (choose the name)
- [x] Modify the README in this branch
- [x] Push it (and the branch) to the repository
- [x] create the pull request for it

**Comment by bkheira** [comment]
Je n'arrive pas à download the repository using command line, je cherche encore comment faire...

**Comment by bkheira** [comment]
Quand je fais `git clone git@github.com:ipop-up/doridot-sncell.git` j'ai le retour suivant : 
Cloning into 'doridot-sncell'...
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

**Comment by bkheira** [comment]
Ai réussi en utilisant le lien https plutôt que ssh
